location: westeurope
name: containerapp-webapp
resourceGroup: Demo-AzureContainerApps
type: Microsoft.App/containerApps
properties:
  managedEnvironmentId: /subscriptions/8daf8b4e-005c-443b-9bd5-2ada95fce462/resourceGroups/rgDemo-ContainerApps/providers/Microsoft.App/managedEnvironments/containerapp-environment
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      allowInsecure: false
      targetPort: 8080
      transport: Auto
  template:
    revisionSuffix: rev-<container_image_tag_wildcard>
    containers:
      - image: acr3v08mk.azurecr.io/webapp:<container_image_tag_wildcard>
        name: containerapp-webapp
        resources:
          cpu: 1.0
          memory: 2Gi
        env:
          - name: HOSTINGSTRATEGY
            value: "Containerized"
          - name: HOSTINGSERVICE
            value: "Azure Container Apps"
        volumeMounts:
          - mountPath: /data
            volumeName: azure-fileshare-volume
        probes:
          - type: liveness
            httpGet:
              path: "/status/liveness"
              port: 8080
              httpHeaders:
              - name: "Custom-Header"
                value: "liveness probe"
            initialDelaySeconds: 10
            periodSeconds: 60
          - type: readiness
            httpGet:
              path: "/status/readiness"
              port: 8080
              httpHeaders:
              - name: "Custom-Header"
                value: "readiness probe"
            initialDelaySeconds: 10
            periodSeconds: 5
          - type: startup
            httpGet:
              path: "/status/startup"
              port: 8080
              httpHeaders:
              - name: "Custom-Header"
                value: "startup probe"
            initialDelaySeconds: 3
            periodSeconds: 3
    scale:
      minReplicas: 1
      maxReplicas: 5
      rules:
      - name: azure-http-requests
        custom:
            type: http
            metadata:
                concurrentRequests: 100
      - name: keda-cpu
        custom:
          type: cpu
          metadata:
            type: Utilization
            value: 80
      - name: keda-ram
        custom:
          type: memory
          metadata:
            type: Utilization
            value: 80
    volumes:
      - name: azure-fileshare-volume
        storageType: AzureFile
        storageName: azure-fileshare-volume
