apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
  namespace: user-workloads
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: container-webapp
          image: <azure_container_registry_wildcard>.azurecr.io/webapp:<container_image_tag_wildcard>
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: service-webapp
  namespace: user-workloads
  labels:
    app: webapp
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.15.1
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
