# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Push Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: dotnet build --no-restore
      
    - name: Test Solution
      run: dotnet test --no-build --verbosity normal

    - name: Login to Azure
      run: az login --service-principal --username ${{ secrets.AZURE_SERVICE_PRINCIPAL }} --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}

    - name: Get Latest Container Image Tag
      id: get_tag
      run: |
        TAG=$(az acr repository show-tags --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} --repository webapp --orderby time_desc --output tsv --detail | head -n 1 | awk '{print $4}')
        NUMERIC_TAG=$(echo "$TAG" | grep -oE '[0-9]+')
        INCREMENTED_TAG=$((NUMERIC_TAG + 1))
        UPDATED_TAG=$(echo "$TAG" | sed "s/$NUMERIC_TAG/$INCREMENTED_TAG/")
        echo "::set-output name=image_tag::$UPDATED_TAG"

    - name: Build and Push Image
      run: |
        docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} &&
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/webapp:${{ steps.get_tag.outputs.image_tag }} -f WebApp/Dockerfile . &&
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/webapp:${{ steps.get_tag.outputs.image_tag }}

